spring:
  datasource:
    url: jdbc:mysql://localhost/tacoapp
    username: tacouser
    password: tacopassword

  logging:
    level:
      root: WARN
      org.springframework.security: DEBUG

  application:
    name: Tacos-app

  thymeleaf:
    cache: false

taco:
  order:
    pageSize: 10