spring:
  datasource:
    generate-unique-name: false
    name: taco-app

  thymeleaf:
    cache: false

  application:
    name: Tacos-app

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG

taco:
  order:
    pageSize: 10

#---
#spring:
#  profiles: prod
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/app
#    username: root
#    password: pa66word
#
#logging:
#  level:
#    tacos: WARN